- name: maya
  label: Maya
  versions:
    # simple version name only (name and labels is match, default exec paths)
    - name: 2024
    - name: 2025

- name: nuke
  label: Nuke X
  # custom args for all versions
  launch_args:
    - "--nukex"
  versions:
    - name: 15-0
      label: 15.0v2
      # custom env
      env:
        CUSTOM_ENV: MY-VALUE
      # custom args for version
      arguments:
        - "--nukex"

- name: houdini
  label: Houdini
  versions:
    - name: 20.0.547
      label: 20.0.547
      environment: {}
      executables:
        windows:
          - "c:/cg-soft/houdini/20.0.123/bin/houdinifx.exe"
        linux:
          - "/opt/hfs20.0.123/bin/houdinifx"
      arguments:
        windows:
          - "dsad"
          - "dasd"
        linux:
          - "--arg"


