- name: maya
  label: Maya
  versions:
    - name: 2024
      executables:
        windows:
          - "C:\Program Files\Autodesk\Maya2024\bin\maya.exe"
#        linux:
#          - "/usr/autodesk/maya2024/bin/maya"
    - name: 2025
#      executables:
#        windows:
#          - "C:\Program Files\Autodesk\Maya2025\bin\maya.exe"
#        linux:
#          - "/usr/autodesk/maya2025/bin/maya"

- name: nuke
  label: Nuke X
  versions:
    - name: 15-0
      label: 15.0v2
      env:
        KEY: VALUE
      launch_args:
        - "--nukex"
      executables:
        linux:
          launch_args:
            - "--nukex"
